name: GitHub Actions Demo
on: push
jobs:
    Explore-GitHub-Actions:
        runs-on: ubuntu-lateset
        steps:
            - name: Print the triggering event
              run: echo "The job was triggered by ${{github.event_name}}."

            - name: Print the OS of the runner
              run: echo "This job is running on a ${{runner.os}} server."

            - name: Print the branch 
              run: echo "The name of ur branch is ${{github.ref}}."

            - name: Check out the repo code action
              uses: actions/checkout@v4

            - run: echo "Cloning the ${{github.repository}} repo."

            - name: List files in the repo
              run: ls ${{github.workspace}}